   name: CompileTCHANZ

   on:
     push:
       branches: [ main]
     pull_request:
       branches: [ main]

   jobs:
    build:
      runs-on: ubuntu-18.04
      steps:
      - name: install dependency
        run: sudo apt install libgtkmm-3.0-dev
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make build
      - name: test application
        run: make test
      - name: Upload
        uses: actions/upload-artifact@v1
        with:
          path: ./projet
          name: projet
