   name: CompileTCHANZ

   on:
     push:
       branches: [ main, rendu2 ]
     pull_request:
       branches: [ main, rendu2 ]

   jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: build application
        run: make build
      - name: test application
        run: make test
